### PR TITLE
ci: add run tests

### PR DESCRIPTION
**Pull request by KyleTryon**

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/bats?version=dev:01dfde802e4f41e8c198cbd1273704cee3575f48

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/bats?version=dev:8e6d8e131d7716df0d5f31dc30d468ca07e08908

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/bats?version=dev:33069be2bb0f14c0f26f9894d8b72316bd7d3bc1

**Review by EricRibeiro — APPROVED** [review]

**Review by ryanwohara — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/bats?version=dev:0e7c1fcda24b3f9f354c7474c84f03e4934fe474

**Pull request merged**
