### PR TITLE
Output JUnit tests

### PR DESCRIPTION
**Pull request by Peter-Darton-i2**
Attempt at resolving issue #4

### CODE REVIEW

**Comment by Peter-Darton-i2** [comment]
@KyleTryon You don't have to choose between console-friendly TAP format and CircleCI-friendly JUnit format; you can have the best of both worlds at the same time because BATS has both a `--formatter` option which is used to output to stdout, and a `--report-formatter` option that outputs to whereever the `--output` flag says it should go.

Take a peek at [my code](https://github.com/CircleCI-Public/BATS-orb/pull/6/files#diff-54561d8330ff868a36334b2c114f566d64e5ba4a4c96dcd5b7569e854eed3b82R26) for example - that's outputting in TAP format to the console (so it looks the same as it always did), as well as generating a JUnit report that's passed to CircleCI.

I'd suggest that, if you want to fully parameterise everything, instead of giving folks an "either TAP or JUnit" choice, give them the option to control both the `formatter` and the `report-formatter` options through parameters (my code hard-coded the JUnit report part; that _could_ be made conditional in the shell script on the user not giving their own report formatter if you really wanted things to be 100% flexible).
...but make sure that the default behaviour is "TAP to stdout and JUnit to CircleCI" because that's what 99% of folks will want.

**Comment by KyleTryon** [comment]
Ah thank you @Peter-Darton-i2 , let me take another pass at it.

**Comment by KyleTryon** [comment]
Ok #12 should do it for us now I hope 👍

**Comment by Peter-Darton-i2** [comment]
Functionality from this PR has been subsumed into #12. Closing.

**Pull request closed without merging**
