### PR TITLE
chore: Fix typos in run job

### PR DESCRIPTION
**Pull request by adamdmharvey**
Fixes two typos in description of parameters in the run job.

### CODE REVIEW

**Comment by Peter-Darton-i2** [comment]
Glad you made this PR; I've just started using this orb and noticed it too 😁

**Comment by Peter-Darton-i2** [comment]
FYI there's also a typo on the [run.yml](https://github.com/CircleCI-Public/BATS-orb/blob/697364cebab425e3cef0b6e4ea8a6f9d9975a88a/src/jobs/run.yml#L13) file too - `defeault` should be `default`.

**Comment by adamdmharvey** [comment]
@Peter-Darton-i2 Nice eye!  👁️ Added that fix to the mix also, with a slight reword.

**Comment by adamdmharvey** [comment]
Bump @KyleTryon ; doesn't seem to be a `CODEOWNERS` in this repo, so apols for the direct tag as you seem to have been the only contributor/author. 😁

**Comment by KyleTryon** [comment]
Hey all, sorry for the delay. Glad to see folks are using this! Let me get everything up-to-date here. Give me 1-2 days and we'll have this all fixed up new.

**Review by KyleTryon — APPROVED** [review]

**Pull request merged**
